language: ruby
script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-head
  - jruby-19mode
  - rbx-19mode
jdk:
  - openjdk6
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
