language: ruby
script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-head
  - jruby-19mode
jdk:
  - openjdk7
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
